#!/usr/bin/env bash
# Creates a new SFTP user.
set -e

user=$1
passw=$2
userdir="/home/${user}/data"

[[ -z ${user} ]] && {
	printf 'Missing user to create\n'
	exit 1
}

[[ -z ${passw} ]] && {
	printf 'Missing user password\n'
	exit 1 
}

id -u ${user} &>/dev/null && {
	printf "Error, user ${user} already exists\n" >&2
	exit 1
}

adduser --quiet --disabled-password --shell /bin/bash --home /home/${user} --gecos "User" ${user}
echo "${user}:${passw}" | chpasswd
usermod -g sftpusers ${user}
chown root:${user} /home/${user}
chmod 755 /home/${user}

mkdir ${userdir}
chown ${user}:${user} ${userdir}
chmod 755 ${userdir}

printf "User ${user} created.\n"
