#!/usr/bin/env bash
#
# Creates a new SFTP user.
set -e

USER=$1
PASSW=$2
USERHOME="/home/${USER}"
USERDATA="${USERHOME}/data"

[[ -z ${USER} ]] && {
  printf 'Missing username\n'
  exit 1
}

[[ -z ${PASSW} ]] && {
  printf 'Missing user password\n'
  exit 1
}

id -u "${USER}" &>/dev/null && {
  printf "Error, user %s already exists\n" "${USER}" >&2
  exit 1
}

adduser \
  --quiet \
  --disabled-password \
  --shell /bin/bash \
  --home "${USERHOME}" \
  --gecos "User" \
  "${USER}"

echo "${USER}:${PASSW}" | chpasswd

usermod -g sftpusers "${USER}"
chown "root:${USER}" "${USERHOME}"
chmod 755 "${USERHOME}"

# Give user access to their jailed directory
mkdir "${USERDATA}"
chown "${USER}:${USER}" "${USERDATA}"
chmod 755 "${USERDATA}"

printf "User %s created.\n" "${USER}"
