#!/usr/bin/env bash
# Creates a new SFTP user.
set -e

user=$1
passw=$2
userhome="/home/${user}"
userdata="${userhome}/data"

[[ -z ${user} ]] && {
	printf 'Missing user to create\n'
	exit 1
}

[[ -z ${passw} ]] && {
	printf 'Missing user password\n'
	exit 1
}

id -u ${user} &>/dev/null && {
	printf "Error, user ${user} already exists\n" >&2
	exit 1
}

adduser \
  --quiet \
  --disabled-password \
  --shell /bin/bash \
  --home ${userhome} \
  --gecos "User" \
  ${user}

echo "${user}:${passw}" | chpasswd

usermod -g sftpusers ${user}
chown root:${user} ${userhome}
chmod 755 ${userhome}

# Give user access to their jailed directory
mkdir ${userdata}
chown ${user}:${user} ${userdata}
chmod 755 ${userdata}

printf "User ${user} created.\n"
