#!/usr/bin/env bash
#
# Delete a user from sftp access
set -e

USER=$1

[[ -z ${USER} ]] && {
  printf 'Missing user to delete\n'
  exit 1
}

id -u "${USER}" &>/dev/null || {
  printf "Error, user %s doesn't exists\n" "${USER}" >&2
  exit 1
}

rm -rf "/home/${USER:?}"
groupdel "${USER}"
userdel "${USER}"

printf "User %s has been removed.\n" "${USER}"
