#!/usr/bin/env bash
# Delete a user from sftp access
set -e

user=$1

id -u ${user} &>/dev/null || {
	printf "Error, user ${user} doesn't exists\n" >&2
	exit 1
}

rm -rf "/home/${user}"
groupdel ${user}
userdel ${user}

printf "User ${user} has been removed.\n"
