#!/usr/bin/env bash
#
# Initialize server to allow SFTP access to jailed users
set -e

sshd_config='/etc/ssh/sshd_config'
sshd_temp='sshd_config.temp'

# Creates sftpuser group if not already created
getent group sftpusers || groupadd sftpusers

# In case this script has already run before, remove and re-run.
# This adds a `## START_SFTP_CONFIG ##` and a `## END_SFTP_CONFIG ##`
# where the modifications has been applied
sed "/## START_SFTP_CONFIG ##/,/## END_SFTP_CONFIG ##/d" \
  ${sshd_config} >${sshd_temp}

cat ${sshd_temp} >${sshd_config}
rm ${sshd_temp}

# Comment out setting to disable SFTP
sed -i \
  '/^Subsystem.*sftp \/usr\/lib\/openssh\/sftp-server/s/^/#/g' \
  ${sshd_config}

# Append SFTP settings to sshd_config
tab=$'\t'
cat <<EOF >>${sshd_config}
## START_SFTP_CONFIG ##

Subsystem sftp internal-sftp

Match group sftpusers
${tab}ChrootDirectory %%h
${tab}X11Forwarding no
${tab}PermitTunnel no
${tab}AllowAgentForwarding no
${tab}AllowTcpForwarding no
${tab}ForceCommand internal-sftp
${tab}PasswordAuthentication yes

## END_SFTP_CONFIG ##
EOF

systemctl restart sshd
printf "SFTP configuration is set-up.\n"
