#!/usr/bin/env bash
# Initialize server to allow SFTP access to jailed users
set -e

# Creates sftpuser group if not already created
getent group sftpusers || groupadd sftpusers

# In case this script has already run before, remove and re-run.
# This adds a `## START_SFTP_CONFIG ##` and a `## END_SFTP_CONFIG ##`
# where the modifications has been applied
sed "/## START_SFTP_CONFIG ##/,/## END_SFTP_CONFIG ##/d" \
  /etc/ssh/sshd_config >sshd_config.temp

cat sshd_config.temp >/etc/ssh/sshd_config
rm sshd_config.temp

# Comment out setting to disable SFTP
sed -i \
  '/^Subsystem.*sftp \/usr\/lib\/openssh\/sftp-server/s/^/#/g' \
  /etc/ssh/sshd_config

# Append new SFTP settings at end of file
printf "## START_SFTP_CONFIG ##

Subsystem sftp internal-sftp

Match group sftpusers
\tChrootDirectory %%h
\tX11Forwarding no
\tPermitTunnel no
\tAllowAgentForwarding no
\tAllowTcpForwarding no
\tForceCommand internal-sftp
\tPasswordAuthentication yes

## END_SFTP_CONFIG ##" >>/etc/ssh/sshd_config

systemctl restart sshd
printf "SFTP configuration is set-up.\n"
