#!/usr/bin/env bash
#
# Initialize server to allow SFTP access to jailed users
set -e

SSHD_CONFIG='/etc/ssh/sshd_config'
SSHD_TEMP='sshd_config.temp'

# Create sftpuser group if not already created.
getent group sftpusers || groupadd sftpusers

# In case this script has already run before, remove the previous modifications
# so we can run this again safely. This script adds a `## START_SFTP_CONFIG ##`
# and a `## END_SFTP_CONFIG ##` where the modifications have previously been
# applied, so we delete this part as it will get created again.
sed \
  "/## START_SFTP_CONFIG ##/,/## END_SFTP_CONFIG ##/d" \
  ${SSHD_CONFIG} >${SSHD_TEMP}

cat ${SSHD_TEMP} >${SSHD_CONFIG}
rm ${SSHD_TEMP}

# Make sure default setting to disable SFTP is commented.
sed -i \
  '/^Subsystem.*sftp \/usr\/lib\/openssh\/sftp-server/s/^/#/g' \
  ${SSHD_CONFIG}

# Append SFTP settings to the configuration file.
tab=$'\t'
cat <<EOF >>${SSHD_CONFIG}
## START_SFTP_CONFIG ##

Subsystem sftp internal-sftp

Match group sftpusers
${tab}ChrootDirectory %h
${tab}X11Forwarding no
${tab}PermitTunnel no
${tab}AllowAgentForwarding no
${tab}AllowTcpForwarding no
${tab}ForceCommand internal-sftp
${tab}PasswordAuthentication yes

## END_SFTP_CONFIG ##
EOF

systemctl restart sshd
printf "SFTP configuration is set-up.\n"
